// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'integrity_test.dart' as integrity_test;
import 'src/class_a.dart' as src_class_a_test;
import 'src/class_b.dart' as src_class_b_test;
import 'src/class_c.dart' as src_class_c_test;
import 'string_utils_test.dart' as string_utils_test;
import 'test_process_result_test.dart' as test_process_result_test;

void main() {
  string_utils_test.main();
  test_process_result_test.main();
  integrity_test.main();
  src_class_b_test.main();
  src_class_c_test.main();
  src_class_a_test.main();
}
