name: minimal_test

description:
  Minimalist library for testing Dart VM scripts using null-safety features.
  Depends only on the Dart SDK >=2.9.1.

version: 0.0.3

homepage: https://github.com/simphotonics/minimal_test

environment:
  sdk: '>=2.9.1 <3.0.0'

dependencies:

dev_dependencies:

dependency_overrides:
