name: minimal_test

description:
  Minimalist library for testing Dart VM scripts using null-safety features.
  Has no external dependencies other than Dart SDK >=2.9.0.

version: 0.0.9

homepage: https://github.com/simphotonics/minimal_test

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:

dev_dependencies:

dependency_overrides:
