name: simple_test

description: A starting point for Dart libraries or applications.

version: 0.0.1

homepage: https://github.com/simphotonics/simple_test

environment:
  sdk: '>=2.9.1 <3.0.0'

dependencies:
  meta: ^1.2.2

dev_dependencies:
  pedantic: ^1.9.2

dependency_overrides:
  # meta:
  #   git:
  #     url: https://github.com/dart-lang/sdk.git
  #     ref: null_safety-pkgs
  #     path: pkg/meta
