name: minimal_test

description: Minimalist library for testing Dart VM scripts using null-safety
  features. Has no dependencies other than Dart SDK >=2.10.0.

version: 0.1.4-nullsafety

homepage: https://github.com/simphotonics/minimal_test

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: null

dev_dependencies:
  pedantic: ^1.9.2

dependency_overrides: null
