name: minimal_test

description: Minimalist library for testing Dart VM scripts using null-safety
  features. Has no dependencies other than Dart SDK >=2.12.0-0.

version: 2.0.1-nullsafety

homepage: https://github.com/simphotonics/minimal_test

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies: null

dev_dependencies:
  pedantic: ^1.9.2

dependency_overrides: null
